# Generated by Django 3.1.7 on 2021-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_movie_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
