# Generated by Django 3.1.7 on 2021-04-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210408_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='movie_categories',
            new_name='genres',
        ),
    ]
